### ISSUE TITLE
[TODO] "Persist" user configuration in URL params

### ISSUE THREAD

**Issue by pascalwengerter** [miatrinity/railsnew.io#75]
Since I've seen this in another tool (but can't quite remember where):

I'd love it if `railsnew.io` would add the current choise of settings as params to the URL. This way, I'd be able to bookmark and quickly share a specific configuration.

**Comment by miatrinity** [comment]
Hi Pascal,

Great idea!, thanks for the suggestion! This has been requested by other users as well, so it's definitely coming in a future release.

Most likely it will be similar to railsbytes.com - ie rather than having the params in the URL, there will be an URL like railsnew.io/some-uniq-id-here. We are planning to add a LOT of things in the future, so adding everything as URL params might end up looking really messy.

**Comment by pascalwengerter** [comment]
Understood and thanks for the response, closing here (for now)
